name: 'GitHub Action for DigitalOcean - doctl'
description: 'Use doctl to manage your DigitalOcean resources.'
author: 'Andrew Starr-Bochicchio <asb@digitalocean.com>'
branding:
  icon: 'droplet'
  color: 'blue'
inputs:
  version:
    description: 'Version of doctl to install'
    default: 'latest'
  token:
    description: 'DigitalOcean API Token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'